# Generated by Django 3.0.3 on 2020-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaned', models.CharField(choices=[('INC', 'Incomplete'), ('COM', 'Complete')], default='INC', max_length=3)),
                ('returned', models.CharField(choices=[('INC', 'Incomplete'), ('COM', 'Complete')], default='INC', max_length=3)),
            ],
        ),
    ]
