# Generated by Django 3.0.3 on 2020-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('timeBeginning', models.CharField(max_length=5)),
                ('classStudy', models.CharField(max_length=7)),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studyGroupSize', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=2)),
            ],
        ),
    ]
